// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using DataAccessLayer.Entities;

namespace DataAccessLayer
{
    public partial class AppDbContext
    {

        [DbFunction("fn_getproduct", "dbo")]
        public IQueryable<fn_getproductResult> fn_getproduct(int? ProductId)
        {
            return FromExpression(() => fn_getproduct(ProductId));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_getproductResult>().HasNoKey();
        }
    }
}
